/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as LaCliniqueRouteImport } from './routes/la-clinique'
import { Route as NousJoindreRouteImport } from './routes/nous-joindre'
import { Route as PourquoiConsulterRouteImport } from './routes/pourquoi-consulter'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as EquipeIndexRouteImport } from './routes/equipe.index'
import { Route as EquipeAlidaFarrellRouteImport } from './routes/equipe.alida-farrell'
import { Route as EquipeNicoleDefoyRouteImport } from './routes/equipe.nicole-defoy'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const LaCliniqueRoute = LaCliniqueRouteImport.update({
  id: '/la-clinique',
  path: '/la-clinique',
  getParentRoute: () => rootRouteImport,
} as any)
const NousJoindreRoute = NousJoindreRouteImport.update({
  id: '/nous-joindre',
  path: '/nous-joindre',
  getParentRoute: () => rootRouteImport,
} as any)
const PourquoiConsulterRoute = PourquoiConsulterRouteImport.update({
  id: '/pourquoi-consulter',
  path: '/pourquoi-consulter',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeIndexRoute = EquipeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipeRoute,
} as any)
const EquipeAlidaFarrellRoute = EquipeAlidaFarrellRouteImport.update({
  id: '/alida-farrell',
  path: '/alida-farrell',
  getParentRoute: () => EquipeRoute,
} as any)
const EquipeNicoleDefoyRoute = EquipeNicoleDefoyRouteImport.update({
  id: '/nicole-defoy',
  path: '/nicole-defoy',
  getParentRoute: () => EquipeRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/coaching': typeof CoachingRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/la-clinique': typeof LaCliniqueRoute
  '/nous-joindre': typeof NousJoindreRoute
  '/pourquoi-consulter': typeof PourquoiConsulterRoute
  '/services': typeof ServicesRouteWithChildren
  '/equipe/alida-farrell': typeof EquipeAlidaFarrellRoute
  '/equipe/nicole-defoy': typeof EquipeNicoleDefoyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/equipe/': typeof EquipeIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/coaching': typeof CoachingRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/la-clinique': typeof LaCliniqueRoute
  '/nous-joindre': typeof NousJoindreRoute
  '/pourquoi-consulter': typeof PourquoiConsulterRoute
  '/equipe/alida-farrell': typeof EquipeAlidaFarrellRoute
  '/equipe/nicole-defoy': typeof EquipeNicoleDefoyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/equipe': typeof EquipeIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/coaching': typeof CoachingRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/la-clinique': typeof LaCliniqueRoute
  '/nous-joindre': typeof NousJoindreRoute
  '/pourquoi-consulter': typeof PourquoiConsulterRoute
  '/services': typeof ServicesRouteWithChildren
  '/equipe/alida-farrell': typeof EquipeAlidaFarrellRoute
  '/equipe/nicole-defoy': typeof EquipeNicoleDefoyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/equipe/': typeof EquipeIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/coaching'
    | '/conditions'
    | '/confidentialite'
    | '/equipe'
    | '/la-clinique'
    | '/nous-joindre'
    | '/pourquoi-consulter'
    | '/services'
    | '/equipe/alida-farrell'
    | '/equipe/nicole-defoy'
    | '/services/$slug'
    | '/equipe/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/coaching'
    | '/conditions'
    | '/confidentialite'
    | '/la-clinique'
    | '/nous-joindre'
    | '/pourquoi-consulter'
    | '/equipe/alida-farrell'
    | '/equipe/nicole-defoy'
    | '/services/$slug'
    | '/equipe'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/coaching'
    | '/conditions'
    | '/confidentialite'
    | '/equipe'
    | '/la-clinique'
    | '/nous-joindre'
    | '/pourquoi-consulter'
    | '/services'
    | '/equipe/alida-farrell'
    | '/equipe/nicole-defoy'
    | '/services/$slug'
    | '/equipe/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CoachingRoute: typeof CoachingRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  EquipeRoute: typeof EquipeRouteWithChildren
  LaCliniqueRoute: typeof LaCliniqueRoute
  NousJoindreRoute: typeof NousJoindreRoute
  PourquoiConsulterRoute: typeof PourquoiConsulterRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-clinique': {
      id: '/la-clinique'
      path: '/la-clinique'
      fullPath: '/la-clinique'
      preLoaderRoute: typeof LaCliniqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nous-joindre': {
      id: '/nous-joindre'
      path: '/nous-joindre'
      fullPath: '/nous-joindre'
      preLoaderRoute: typeof NousJoindreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pourquoi-consulter': {
      id: '/pourquoi-consulter'
      path: '/pourquoi-consulter'
      fullPath: '/pourquoi-consulter'
      preLoaderRoute: typeof PourquoiConsulterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/': {
      id: '/equipe/'
      path: '/'
      fullPath: '/equipe/'
      preLoaderRoute: typeof EquipeIndexRouteImport
      parentRoute: typeof EquipeRoute
    }
    '/equipe/alida-farrell': {
      id: '/equipe/alida-farrell'
      path: '/alida-farrell'
      fullPath: '/equipe/alida-farrell'
      preLoaderRoute: typeof EquipeAlidaFarrellRouteImport
      parentRoute: typeof EquipeRoute
    }
    '/equipe/nicole-defoy': {
      id: '/equipe/nicole-defoy'
      path: '/nicole-defoy'
      fullPath: '/equipe/nicole-defoy'
      preLoaderRoute: typeof EquipeNicoleDefoyRouteImport
      parentRoute: typeof EquipeRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface EquipeRouteChildren {
  EquipeAlidaFarrellRoute: typeof EquipeAlidaFarrellRoute
  EquipeNicoleDefoyRoute: typeof EquipeNicoleDefoyRoute
  EquipeIndexRoute: typeof EquipeIndexRoute
}

const EquipeRouteChildren: EquipeRouteChildren = {
  EquipeAlidaFarrellRoute: EquipeAlidaFarrellRoute,
  EquipeNicoleDefoyRoute: EquipeNicoleDefoyRoute,
  EquipeIndexRoute: EquipeIndexRoute,
}

const EquipeRouteWithChildren =
  EquipeRoute._addFileChildren(EquipeRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CoachingRoute: CoachingRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  EquipeRoute: EquipeRouteWithChildren,
  LaCliniqueRoute: LaCliniqueRoute,
  NousJoindreRoute: NousJoindreRoute,
  PourquoiConsulterRoute: PourquoiConsulterRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
